import type { Metadata } from "next";
import Navigation from "./components/Navigation";
import Logo from "./components/Logo";

export const metadata: Metadata = {
  title: "The wild oasis",
  // description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>
        <header>
          <Logo />
          <Navigation />
        </header>
        <main>{children}</main>
        <footer>Copyrights by the Wild oasis</footer>
      </body>
    </html>
  );
}
